### ISSUE TITLE
It seem that commands like TerminalName, etc that should return string return only one character

### ISSUE THREAD

**Issue by claudiutraistaru** [rmawatson/PyMT4#8]
Running in python TerminalName() gets only the first character , the same for all the commands that should return a string , like OrderSymbol, etc.

After some diging I found a fix that can be applied on the mql side, 

 case CmdId_TerminalName:
              StringToCharArray(TerminalName(), result_string);
	      pymt4_setStringResult(result_string,GetLastError());
	      break;

this , after you declare result_string[] as uchar. I hope this helps.

**Comment by rmawatson** [comment]
This problem is because they have changed in newer MT4 to using wchar_t rather than char, I changed the code to use wchar_t. What build are you using?
Also, originally the evaluation order was left to right in function calls. But it seems in the latest builds this is not defined, so the MQL side should all be changed to assign to temporaries before calling pymt4_xxxx() calls. otherwise GetLastError() could be called before any function call before it.. 
pymt4_setStringResult(SomeOtherFunc(), GetLastError());
should be changed to something like
T arg1 = SomeOtherFunc();int err = GetLastError();
pymt4_setStringResult(arg1,err);
Where T is the correct type for the return of SomeOTherFunc();






Date: Thu, 2 Jul 2015 15:14:02 -0700

**Comment by claudiutraistaru** [comment]
I`ve tried your solution , somehow it doesn`t return anything , maybe I did something wrong.

**Comment by rmawatson** [comment]
Ok - right.

Looking at the code, the last commit I did to fix getStringArgument() was only half the fix.

As MT4 has moved to wide char, any of the dll functions (server side) like the one below, need to be updated to take wchar_t. not char anymore. 	std::string resultString(result); will no longer work if result is wchar_t*, and will need to be converted.

EXPORT(BOOL) pymt4_setStringResult(const char* result,int32_t error)
{
	std::string resultString(result);
	IOServerPtr ioserver = IOServer::Instance();
	ioserver->completeCommand<std::string>(resultString,error);
	return TRUE;
}


Your solution is converting it already to a char array, so this is why its working. Better place to apply this fix would be in the above functions however, so you do not have to add StringToCharArray everywhere in the MQL.

**Comment by rmawatson** [comment]
Fixed a few of these.
